name: ADD
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - pytorch=2.0.1
  - torchvision
  # - cudatoolkit=12.3
  - tqdm
  - matplotlib
  - scikit-learn
  - pip
  - pip:
    - torchaudio==2.0.1
    - timm
    - wandb
    - transformers
