name: fake-voice-detection
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - numpy
  - pytorch=1.12.1
  - torchvision=0.13.1
  - cudatoolkit=11.3
  - tqdm
  - matplotlib
  - scikit-learn
  - pip
  - pip:
    - torchaudio==0.12.1
    - timm
    - wandb
    - transformers
